import re
import logging
import time
from playwright.sync_api import Playwright, sync_playwright, expect

logging.basicConfig(level=logging.INFO, format='%(asctime)s %(levelname)s %(message)s')


def run(playwright: Playwright) -> None:
    logging.info("Test 1: iniciar teste de compra de cliente")
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("http://localhost:8080/")
    logging.info("1: navegado para homepage")
    page.get_by_role("link", name=" Login").click()
    logging.info("1: clique no link de Login")
    page.get_by_role("textbox", name=" Email").click()
    page.get_by_role("textbox", name=" Email").fill("breno@teste.com")
    page.get_by_role("textbox", name=" Email").press("Tab")
    page.get_by_role("textbox", name=" Senha").press("CapsLock")
    page.get_by_role("textbox", name=" Senha").fill("B")
    page.get_by_role("textbox", name=" Senha").press("CapsLock")
    page.get_by_role("textbox", name=" Senha").fill("@")
    page.get_by_role("button", name=" Entrar").click()
    logging.info("1: submeteu credenciais e clicou Entrar")
    time.sleep(2)
    page.get_by_role("link", name=" Livros").click()
    logging.info("1: navegou para Livros")
    time.sleep(2)
    page.get_by_role("row", name="LIV001 Dom Casmurro Companhia").get_by_role("button").click()
    page.get_by_role("button").nth(2).dblclick()
    page.get_by_role("link", name=" Continuar Comprando").click()
    page.get_by_role("row", name="LIV002 A Hora da Estrela").get_by_role("button").click()
    page.get_by_role("button", name=" Prosseguir com Pagamento").click()
    time.sleep(2)
    page.get_by_role("button", name=" Adicionar novo endereço").click()
    page.get_by_role("textbox", name="Nome do Endereço (ex: Casa,").click()
    page.get_by_role("textbox", name="Nome do Endereço (ex: Casa,").click()
    page.get_by_role("textbox", name="Nome do Endereço (ex: Casa,").click()
    page.get_by_role("textbox", name="Nome do Endereço (ex: Casa,").fill("novo endereco teste")
    page.get_by_role("textbox", name="Nome do Endereço (ex: Casa,").press("Tab")
    page.get_by_label("Tipo de Residência *").select_option("CASA")
    page.get_by_text("Tipo de Residência * Selecione... Casa Apartamento Comércio Galpão Outros Tipo").click()
    page.get_by_label("Tipo de Endereço *").select_option("COBRANCA")
    page.locator(".col-md-4").first.click()
    page.get_by_role("textbox", name="CEP *").click()
    page.get_by_role("textbox", name="CEP *").fill("11111-1111")
    page.get_by_role("textbox", name="CEP *").press("Tab")
    page.get_by_role("textbox", name="Logradouro (Rua, Avenida, etc").fill("teste")
    page.get_by_role("textbox", name="Logradouro (Rua, Avenida, etc").press("Tab")
    page.get_by_role("textbox", name="Numero * Número do Cartão (16").fill("11111")
    page.get_by_role("textbox", name="Bairro *").click()
    page.get_by_role("textbox", name="Bairro *").fill("bairro teste")
    page.get_by_role("textbox", name="Bairro *").press("Tab")
    page.get_by_role("textbox", name="Cidade *").fill("cidade teste")
    page.get_by_role("textbox", name="Cidade *").press("Tab")
    page.get_by_role("textbox", name="Estado *").fill("sp")
    page.get_by_role("textbox", name="Estado *").press("Tab")
    page.get_by_role("textbox", name="País *").fill("brasil")
    page.get_by_role("button", name=" Salvar").click()
    page.get_by_role("textbox", name="Digite seu código de cupom").click()
    page.get_by_role("textbox", name="Digite seu código de cupom").press("CapsLock")
    page.get_by_role("textbox", name="Digite seu código de cupom").fill("BEMVINDO10")
    page.get_by_role("textbox", name="Digite seu código de cupom").press("CapsLock")
    page.get_by_role("button", name=" Aplicar").click()
    page.get_by_role("button", name=" Adicionar novo cartão").click()
    page.get_by_role("textbox", name="0000000000000000").click()
    page.get_by_role("textbox", name="0000000000000000").fill("1111111111111111")
    page.get_by_role("textbox", name="Nome Impresso no Cartão *").click()
    page.get_by_role("textbox", name="Nome Impresso no Cartão *").press("CapsLock")
    page.get_by_role("textbox", name="Nome Impresso no Cartão *").fill("B")
    page.get_by_role("textbox", name="Nome Impresso no Cartão *").press("CapsLock")
    page.get_by_role("textbox", name="Nome Impresso no Cartão *").fill("Breno teste")
    page.get_by_label("Bandeira *").select_option("VISA")
    page.get_by_role("textbox", name="CVV/CVC (3-4 dígitos) *").click()
    page.get_by_role("textbox", name="CVV/CVC (3-4 dígitos) *").fill("1234")
    page.get_by_text("Definir como cartão").click()
    page.get_by_role("button", name=" Salvar cartão").click()
    page.locator("div:nth-child(2) > .form-check").first.click()
    page.get_by_role("radio", name="novo endereco teste - teste,").check()
    page.get_by_role("radio", name="novo endereco teste - teste,").check()
    page.get_by_placeholder("0,00").first.click()
    page.get_by_placeholder("0,00").first.fill("10")
    page.get_by_placeholder("0,00").first.press("Tab")
    page.get_by_role("textbox", name="Digite seu código de cupom").click()
    page.get_by_role("textbox", name="Digite seu código de cupom").press("CapsLock")
    page.get_by_role("textbox", name="Digite seu código de cupom").fill("BEMVINDO10")
    page.get_by_role("button", name=" Aplicar").click()
    page.get_by_placeholder("0,00").nth(1).click()
    page.get_by_placeholder("0,00").nth(1).fill("48.9")
    page.get_by_role("checkbox", name="Concordo com os termos e").check()
    page.get_by_role("button", name=" Finalizar Compra").click()
    logging.info("1: Finalizou compra (clicou Finalizar Compra)")
    time.sleep(3)
    # ---------------------

with sync_playwright() as playwright:
    run(playwright)
