name: Validate HTML

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download vnu.jar
        run: |
          curl -L -o vnu.zip https://github.com/validator/validator/releases/latest/download/vnu.jar.zip
          unzip vnu.zip

      - name: Validate HTML
        run: java -jar dist/vnu.jar --skip-non-html --errors-only .